[package]
name = "cut-trailing-bytes"
version = "0.1.0"
authors = ["zhuangqiubin <zhuangqiubin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = { version = "0.3"}
indicatif = "0.16.2"
humansize = "1.1.1"
