name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: |
        ls -l
        ls -l .\target\
        ls -l .\target\release\
        
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        path: target\release\cut-trailing-bytes.exe
